# Generated by Django 5.2 on 2025-09-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_accomplissement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'accomplissement"),
        ),
        migrations.AddField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=10, verbose_name='priorité'),
        ),
    ]
